name: Run CLI test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Build dux
        run: |
          go build
      - name: Run dux
        run: |
          ./dux .
